### PR TITLE
Added new column Publish to caseEvents

### PR DESCRIPTION
**Pull request by indvamshi**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-358

### Change description ###

Added new column 'Publish' to case events to say if an event can be published

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Review by lewisbirks — CHANGES_REQUESTED** [review]
Hi @indvamshi, whilst I know nothing about the details you are adding (it would be useful to get someone who does to approve the request) can you please add some tests ensuring that data is read into the new column of the spreadsheet properly.

**Review by makowalski — APPROVED** [review]
LGTM

**Review by lewisbirks — COMMENTED** [review]
if @makowalski is happy with the change from a technical point of view then I am fine to approve as long as it works with the current versions of the ccd definition store

**Review by makowalski — APPROVED** [review]
LGTM

**Review by lewisbirks — APPROVED** [review]

**Pull request merged**
